#!/bin/bash

# Check for virtual environement
if [[ -n "$VIRTUAL_ENV" ]]; then
	echo "You are in a virtual environment: $VIRTUAL_ENV"
	echo "Deactivating ..."
	deactivate
else
	echo "You are not in a virtual environment."
	echo "Continuing"
fi

echo "Removing env"
rm -rf env

echo "Creating new venv with name env"
python3 -m venv env

echo "Upgrading pip"
env/bin/pip install --upgrade pip

echo "Installing requirements"
env/bin/pip install -r requirements.txt

echo ""
echo "Done. Activate with: source env/bin/activate"
