#!/bin/bash

# Check for virtual environement
if [[ -n "$VIRTUAL_ENV" ]]; then
	echo "You are in a virtual environment: $VIRTUAL_ENV"
	echo "Deactivating ..."
	deactivate
else
	echo "You are not in a virtual environment."
	echo "Continuing"
fi

echo "Removing env"
rm -rf env

echo "Creating new venv with name env"
python3 -m venv env

echo "Activating env"
source env/bin/activate

echo "Upgrading pip"
python3 -m pip install --upgrade pip

echo "Installing requirements"
python3 -m pip install -r requirements.txt
